import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Check, FileText, X } from 'lucide-react';
import api from '../lib/api';
import { useAuth } from '../context/AuthContext';

const money = (n, currency = 'INR') => new Intl.NumberFormat('en-IN', { style: 'currency', currency }).format(n || 0);
export default function InvoiceDetailPage() {
  const { id } = useParams();
  const cache = useQueryClient();
  const { user } = useAuth();
  const [draft, setDraft] = useState(null);
  const [actionError, setActionError] = useState('');
  const [decisionComment, setDecisionComment] = useState('');
  const [holdReason, setHoldReason] = useState('');
  const vendors = useQuery({ queryKey: ['vendors'], queryFn: async () => (await api.get('/vendors')).data.data.vendors, enabled: Boolean(user) });
  const { data, isLoading, error } = useQuery({ queryKey: ['invoice', id], queryFn: async () => (await api.get(`/invoices/${id}`)).data.data.invoice });
  const history = useQuery({ queryKey: ['invoice-history', id], queryFn: async () => (await api.get(`/invoices/${id}/history`)).data.data.history });
  const save = useMutation({
    mutationFn: async (body) => (await api.patch(`/invoices/${id}`, body)).data.data.invoice,
    onSuccess: (invoice) => { cache.setQueryData(['invoice', id], invoice); cache.invalidateQueries({ queryKey: ['invoice', id] }); cache.invalidateQueries({ queryKey: ['invoice-history', id] }); cache.invalidateQueries({ queryKey: ['invoices'] }); setDraft(null); setActionError(''); },
    onError: (err) => setActionError(err.response?.data?.message || 'Could not save these changes.'),
  });
  const decide = useMutation({
    mutationFn: async (decision) => (await api.post(`/invoices/${id}/decision`, { decision, comment: decisionComment })).data.data.invoice,
    onSuccess: (invoice) => { cache.setQueryData(['invoice', id], invoice); cache.invalidateQueries({ queryKey: ['invoice', id] }); cache.invalidateQueries({ queryKey: ['approval-queue'] }); cache.invalidateQueries({ queryKey: ['invoices'] }); cache.invalidateQueries({ queryKey: ['invoice-history', id] }); setDecisionComment(''); setActionError(''); },
    onError: (err) => setActionError(err.response?.data?.message || 'Could not save the decision.'),
  });
  const holdAction = useMutation({
    mutationFn: async ({ release, reason }) => (await api.post(`/invoices/${id}/${release ? 'release-hold' : 'hold'}`, release ? { reason } : { reason })).data.data.invoice,
    onSuccess: (invoice) => { cache.setQueryData(['invoice', id], invoice); cache.invalidateQueries({ queryKey: ['invoice', id] }); cache.invalidateQueries({ queryKey: ['approval-queue'] }); cache.invalidateQueries({ queryKey: ['invoices'] }); cache.invalidateQueries({ queryKey: ['invoice-history', id] }); setHoldReason(''); setActionError(''); },
    onError: (err) => setActionError(err.response?.data?.message || 'Could not update the hold status.'),
  });
  if (isLoading) return <div className="table-message">Loading invoice…</div>;
  if (error || !data) return <div className="module-page"><Link className="back-link" to="/invoices"><ArrowLeft size={15} /> Invoices</Link><div className="table-message error-text">This invoice could not be loaded.</div></div>;
  const isSubmitter = data.uploadedBy?._id === user?.id;
  const canResolve = ['pending_review', 'pending_approval', 'rejected'].includes(data.status) && ['clerk', 'admin'].includes(user?.role) && (user?.role !== 'clerk' || isSubmitter);
  const canDecide = data.status === 'pending_approval' && ['manager', 'admin'].includes(user?.role);
  const canManageHold = ['manager', 'admin'].includes(user?.role);
  const values = draft || { invoiceNumber: data.invoiceNumber, vendorId: data.vendor?._id || '', invoiceDate: data.invoiceDate?.slice(0, 10) || '', dueDate: data.dueDate?.slice(0, 10) || '', totalAmount: data.totalAmount, currency: data.currency || 'INR', exceptionNotes: data.exceptionNotes || '' };
  const setField = (field, value) => setDraft({ ...values, [field]: value });
  return <section className="module-page">
    <Link className="back-link" to="/invoices"><ArrowLeft size={15} /> Back to invoices</Link>
    <div className="page-heading"><div><span className="welcome-tag">INVOICE RECORD</span><h1>{data.invoiceNumber}</h1><p>Uploaded {new Date(data.createdAt).toLocaleString('en-IN')}</p></div><span className={`status-pill status-${data.status}`}>{data.status.replaceAll('_', ' ')}</span></div>
    <div className="detail-grid">
      <article className="detail-card"><h2>Invoice summary</h2><dl className="detail-list"><div><dt>Selected vendor</dt><dd>{data.vendor?.companyName}</dd></div><div><dt>Invoice date</dt><dd>{data.invoiceDate ? new Date(data.invoiceDate).toLocaleDateString('en-IN') : 'Not detected'}</dd></div><div><dt>Due date</dt><dd>{data.dueDate ? new Date(data.dueDate).toLocaleDateString('en-IN') : 'Not detected'}</dd></div><div><dt>Total amount</dt><dd className="amount-cell">{money(data.totalAmount, data.currency)}</dd></div><div><dt>OCR confidence</dt><dd>{data.ocrConfidenceScore ? `${Math.round(data.ocrConfidenceScore)}%` : '—'}</dd></div><div><dt>Purchase order</dt><dd>{data.purchaseOrder?.poNumber || 'Not linked'}</dd></div></dl>{data.ocrExtractedData?.rawVendorName && !['invoice', 'tax invoice', 'bill'].includes(data.ocrExtractedData.rawVendorName.trim().toLowerCase()) && <p className="vendor-ocr-note">Text on invoice says “{data.ocrExtractedData.rawVendorName}”. Check that the selected vendor is the same business.</p>}</article>
      <article className="detail-card"><h2>Original document</h2>{data.originalFileUrl ? <a className="document-link" href={`${api.defaults.baseURL.replace(/\/api$/, '')}${data.originalFileUrl}`} target="_blank" rel="noreferrer"><FileText size={18} /> View uploaded file</a> : <p className="muted">No document attached.</p>}<h2 className="section-subhead">Vendor contact</h2><p className="vendor-contact">{data.vendor?.contactName}<br /><a href={`mailto:${data.vendor?.email}`}>{data.vendor?.email}</a></p></article>
    </div>
    {data.hasDiscrepancies && <article className="detail-card discrepancy-card"><h2>Purchase order differences</h2><p>Review these values before moving the invoice forward.</p><div className="table-wrap"><table><thead><tr><th>Field</th><th>PO value</th><th>Invoice value</th><th>Difference</th><th>Severity</th></tr></thead><tbody>{data.discrepancies.map((item, index) => <tr key={`${item.field}-${index}`}><td>{item.field}</td><td>{item.poValue ?? '—'}</td><td>{item.invoiceValue ?? '—'}</td><td>{item.percentageDiff}%</td><td><span className={`severity severity-${item.severity}`}>{item.severity}</span></td></tr>)}</tbody></table></div></article>}
    {canResolve && <article className="detail-card resolution-card"><h2>Review invoice</h2><p>Correct any details OCR read incorrectly. Add exception notes if there are purchase order differences.</p><div className="form-grid"><label className="field-label">Vendor<select value={values.vendorId} onChange={(e) => setField('vendorId', e.target.value)}>{(vendors.data || []).map((vendor) => <option key={vendor._id} value={vendor._id}>{vendor.companyName}</option>)}</select></label><label className="field-label">Invoice number<input value={values.invoiceNumber} onChange={(e) => setField('invoiceNumber', e.target.value)} /></label><label className="field-label">Total amount<input type="number" min="0" step="0.01" value={values.totalAmount} onChange={(e) => setField('totalAmount', e.target.value)} /></label><label className="field-label">Currency<select value={values.currency} onChange={(e) => setField('currency', e.target.value)}>{['INR', 'USD', 'AUD', 'CAD', 'EUR'].map((code) => <option key={code}>{code}</option>)}</select></label><label className="field-label">Invoice date<input type="date" value={values.invoiceDate} onChange={(e) => setField('invoiceDate', e.target.value)} /></label><label className="field-label">Due date<input type="date" value={values.dueDate} onChange={(e) => setField('dueDate', e.target.value)} /></label></div>{data.hasDiscrepancies && <label className="field-label">Exception notes<textarea rows="3" value={values.exceptionNotes} onChange={(e) => setField('exceptionNotes', e.target.value)} placeholder="Explain the difference or why this invoice should proceed." /></label>}{actionError && <p className="inline-error">{actionError}</p>}<div className="upload-actions"><button className="secondary-button" type="button" onClick={() => save.mutate(values)} disabled={save.isPending}>Save corrections</button><button className="primary-link" type="button" onClick={() => save.mutate({ ...values, submitForApproval: true })} disabled={save.isPending}>Submit for approval</button></div></article>}
    {canDecide && <article className="detail-card resolution-card"><h2>Manager decision</h2><p>Check the invoice and uploaded document, then record your decision with a note for the team.</p><label className="field-label">Decision comment<textarea rows="3" maxLength="2000" value={decisionComment} onChange={(e) => setDecisionComment(e.target.value)} placeholder="Explain your approval or what needs to be corrected." /></label>{actionError && <p className="inline-error">{actionError}</p>}<div className="upload-actions"><button className="secondary-button decision-reject" type="button" onClick={() => decide.mutate('reject')} disabled={decide.isPending || !decisionComment.trim()}><X size={15} /> Reject with changes</button><button className="primary-link" type="button" onClick={() => decide.mutate('approve')} disabled={decide.isPending || !decisionComment.trim()}><Check size={15} /> Approve invoice</button></div></article>}
    {canManageHold && (['pending_approval', 'approved'].includes(data.status) || data.status === 'on_hold') && <article className="detail-card resolution-card"><h2>{data.status === 'on_hold' ? 'Invoice on hold' : 'Pause this invoice'}</h2><p>{data.status === 'on_hold' ? (data.holdReason || 'This invoice was placed on hold in the demo data.') : 'Use On hold when you need to pause work while waiting for information or resolving a concern.'}</p>{data.status !== 'on_hold' ? <><label className="field-label">Reason<textarea rows="2" maxLength="2000" value={holdReason} onChange={(e) => setHoldReason(e.target.value)} placeholder="For example: waiting for a corrected invoice or missing receipt." /></label><div className="upload-actions"><span>The invoice will leave the approval queue until released.</span><button className="secondary-button" type="button" onClick={() => holdAction.mutate({ release: false, reason: holdReason })} disabled={holdAction.isPending || !holdReason.trim()}>Put on hold</button></div></> : <div className="upload-actions"><span>It will return to its previous workflow step.</span><button className="primary-link" type="button" onClick={() => holdAction.mutate({ release: true, reason: holdReason })} disabled={holdAction.isPending}>Release hold</button></div>}{actionError && <p className="inline-error">{actionError}</p>}</article>}
    {data.status === 'rejected' && <article className="detail-card rejection-card"><h2>Changes requested</h2><p>{data.rejectionReason || 'The manager requested corrections.'}</p><small>Update the invoice details above and submit it again for approval.</small></article>}
    {data.comments?.length > 0 && <article className="detail-card history-card"><h2>Team comments</h2><div className="timeline">{data.comments.map((comment, index) => <div className="timeline-row" key={`${comment.createdAt}-${index}`}><span className="timeline-dot" /><div><b>{comment.author?.name || 'Team member'}</b><small>{new Date(comment.createdAt).toLocaleString('en-IN')}</small><p>{comment.text}</p></div></div>)}</div></article>}
    <article className="detail-card history-card"><h2>Status history</h2>{history.isLoading ? <p className="muted">Loading history…</p> : !history.data?.length ? <p className="muted">No history recorded yet.</p> : <div className="timeline">{history.data.map((entry) => <div className="timeline-row" key={entry._id}><span className="timeline-dot" /><div><b>{entry.action.replaceAll('_', ' ').toLowerCase()}</b><small>{entry.performedBy?.name || 'System'} · {new Date(entry.createdAt).toLocaleString('en-IN')}</small><p>{entry.description}</p></div></div>)}</div>}</article>
    <article className="detail-card raw-ocr"><h2>Extracted text</h2><pre>{data.ocrRawText || 'No text was extracted from this document.'}</pre></article>
  </section>;
}
