import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';
import { UserPlus, Users } from 'lucide-react';
import api from '../lib/api';

const initial = { name: '', email: '', password: '', role: 'clerk', department: 'Finance' };
export default function UserManagementPage() {
  const [form, setForm] = useState(initial);
  const [message, setMessage] = useState('');
  const cache = useQueryClient();
  const usersQuery = useQuery({ queryKey: ['users'], queryFn: async () => (await api.get('/auth/users')).data.data.users });
  const create = useMutation({
    mutationFn: async () => (await api.post('/auth/register', form)).data.data.user,
    onSuccess: (user) => { cache.invalidateQueries({ queryKey: ['users'] }); setForm(initial); setMessage(`${user.name} can now sign in as ${user.role}.`); },
    onError: (error) => setMessage(error.response?.data?.message || 'Could not create this account.'),
  });
  return <section className="module-page"><div className="page-heading"><div><span className="welcome-tag">WORKSPACE ACCESS</span><h1>Team members</h1><p>Create clerk and manager accounts for your project team.</p></div></div><div className="detail-grid"><form className="vendor-form" onSubmit={(event) => { event.preventDefault(); setMessage(''); create.mutate(); }}><div className="upload-step-title"><span className="step-number"><UserPlus size={14} /></span><div><b>Add a team member</b><small>Only admins can create accounts.</small></div></div><div className="user-fields"><label className="field-label">Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="field-label">Work email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label className="field-label">Temporary password<input required minLength="6" type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label className="field-label">Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="clerk">Clerk</option><option value="manager">Manager</option></select></label><label className="field-label">Department<input value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /></label></div>{message && <p className="inline-hint" role="status">{message}</p>}<button className="primary-link" disabled={create.isPending}>{create.isPending ? 'Creating…' : 'Create account'}</button></form><article className="detail-card"><div className="card-title-row"><div><h2>Access roles</h2><p>Role determines which actions each team member can take.</p></div><Users size={17} /></div><div className="role-list"><div><b>Admin</b><span>Workspace setup, users, and all records</span></div><div><b>Manager</b><span>Vendors, invoices, and approvals</span></div><div><b>Clerk</b><span>Invoice intake, review, and approved payments</span></div></div></article></div><div className="table-toolbar"><span>{usersQuery.data?.length || 0} team members</span></div>{usersQuery.isLoading ? <div className="table-message">Loading team members…</div> : usersQuery.isError ? <div className="table-message error-text">Could not load accounts.</div> : <div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Department</th><th>Role</th><th>Last sign in</th></tr></thead><tbody>{usersQuery.data.map((user) => <tr key={user._id}><td className="table-primary">{user.name}</td><td>{user.email}</td><td>{user.department}</td><td><span className={`status-pill role-${user.role}`}>{user.role}</span></td><td>{user.lastLogin ? new Date(user.lastLogin).toLocaleDateString('en-IN') : 'Not yet'}</td></tr>)}</tbody></table></div>}</section>;
}
